package com.xingoo.teddy.mapper;

import com.xingoo.teddy.entity.Alert;
import org.apache.ibatis.annotations.*;

@Mapper
public interface AlertMapper {

    @Select("select count(1) from alert")
    Integer count() throws Exception;

    @Update("create table alert(" +
            "id generated by default as identity," +
            "email VARCHAR(500)," +
            "phone VARCHAR(100)," +
            "state VARCHAR(20)," +
            "modify_time TIMESTAMP default CURRENT_TIMESTAMP," +
            "primary key (id))")
    void create();


    @Insert("insert into alert(email,phone,state) values(#{a.email},#{a.phone},#{a.state})")
    Long insert(@Param("a") Alert alert);
}
