package com.xingoo.teddy.mapper;

import com.xingoo.teddy.entity.Job;
import org.apache.ibatis.annotations.*;

@Mapper
public interface JobMapper {

    @Select("select count(1) from job")
    Integer count() throws Exception;

    @Update("create table job(" +
            "id generated by default as identity," +
            "name       VARCHAR(200)," +
            "config_id  BIGINT," +
            "task_id    BIGINT," +
            "alert_id   BIGINT," +
            "restart_id BIGINT," +
            "state      VARCHAR(20)," +
            "modify_time TIMESTAMP default CURRENT_TIMESTAMP," +
            "primary key (id))")
    void create();

    @Insert("insert into job(name,config_id,task_id,alert_id,restart_id,state) " +
            " values(#{j.name},#{j.config_id},#{j.task_id},#{j.alert_id},#{j.restart_id},#{j.state})")
    Long insert(@Param("j") Job job);

//
//    @Update("update task t set t.state = #{state}, t.modify_time = #{now} where t.id = #{id}")
//    void updateStateById(@Param("id")    String id,
//                         @Param("state") String state,
//                         @Param("now") Date now);
//
//    @Select("select * from task where application_id is not null")
//    List<Task> findAllByApplicationId();
//
//    @Select("select * from task where id = #{id}")
//    Task findOne(@Param("id")String id);
//
//    @Insert({"insert into task(id,name,command,create_time,email,send,modify_time) " +
//            "values(#{t.id}, #{t.name}, #{t.command},#{t.create_time}, #{t.email}, #{t.send},#{t.modify_time})"})
//    void save(@Param("t") Task task);
//
//    @Select("select * from task")
//    List<Task> findAll();
//
//    @Delete("delete from task where id = #{id}")
//    void delete(@Param("id") String id);
//
//    @Update("update task set state=#{state}, modify_time=#{mt}, application_id=#{appid} where id = #{id}")
//    void update(@Param("id")    String  id,
//                @Param("state") String  state,
//                @Param("mt")    Date    modifyTime,
//                @Param("appid") String  applicationId);
}
