package com.xingoo.teddy.mapper;

import com.xingoo.teddy.entity.Alert;
import org.apache.ibatis.annotations.*;

@Mapper
public interface RestartMapper {

    @Select("select count(1) from restart")
    Integer count() throws Exception;

    @Update("create table restart(" +
            "id generated by default as identity," +
            "app_id     VARCHAR(500)," +
            "job_id     BIGINT," +
            "task_id    BIGINT," +
            "count      SMALLINT," +
            "state      VARCHAR(20)," +
            "modify_time TIMESTAMP default CURRENT_TIMESTAMP," +
            "primary key (id))")
    void create();

}
