package com.xingoo.teddy.mapper;

import com.xingoo.teddy.entity.Alert;
import com.xingoo.teddy.entity.Task;
import org.apache.ibatis.annotations.*;

@Mapper
public interface TaskMapper {

    @Select("select count(1) from task")
    Integer count() throws Exception;

    @Update("create table task(" +
            "id generated by default as identity," +
            "job_id BIGINT," +
            "app_id VARCHAR(100)," +
            "state  VARCHAR(20)," +
            "url    VARCHAR(200)," +
            "modify_time TIMESTAMP," +
            "primary key (id))")
    void create();

    @Insert("insert into task(job_id) values(#{t.job_id})")
    Long insert(@Param("t") Task task);

}
